config/routes.rb
Rails.application.routes.draw do
  root                  'posts#index'
  get    '/post',   to: 'posts#new', as: 'new_post'
  post   '/post',   to: 'posts#create', as: 'posts'
  get    '/about',  to: 'static_pages#about'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :body,    presence: true, length: { maximum: 500 }
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  # Associations
  has_many :posts, dependent: :destroy
  
  # Callbacks
  before_save :downcase_email

  # Validations
  validates :name,  presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 }, 
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }


  # Remember the user in the database, for use in persistent sessions
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Forget a user
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Return true if remember token matches digest
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Encrypts given token for use in digest
  def User.digest(token)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(token, cost: cost)
  end

  # Generates a new, random token
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  private

    def downcase_email
      email.downcase!
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, only: [:new, :create]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post         = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save
      flash[:success] = "Post created."
      redirect_to root_url
    else
      render 'new'
    end
  end

  private

    def post_params
      params.require(:post).permit(:body)
    end

    def require_login
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to root_url
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      flash[:success] = 'Logged in.'
      redirect_to root_url
    else
      flash.now[:danger] = 'Invalid email/password combination.'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # returns the full page title on a per-page basis
  def full_title(page_title = '')
    base_title = "Members Only"
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    !current_user.nil?
  end

  # Returns the current, logged-in user (if any)
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Remembers user with persistent session
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Forgets persistent user session
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs user out
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <p>Created by Chris Norwood.  Find the source on <a href="https://github.com/chrisnorwood/members-only">GitHub</a>.</p>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-static-top">
  <div class="container">
    <%= link_to "Members Only", root_url, id: 'logo', class: 'navbar-brand' %>
    <ul class="nav navbar-right">
      <li><%= link_to "About", about_path %></li>
      <% if logged_in? %>
        <li><%= link_to "Logout", logout_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Login", login_path %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>

    <div class="container-fluid">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    </div>

    <%= yield %>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/posts/index.html.erb
<% provide(:title, "Secret Posts") %>

<h1>Posts</h1>
<div class="container-fluid col-md-6 col-md-offset-3 posts">
  <% if logged_in? %>
    <%= link_to "Create new post", new_post_path, class: 'btn btn-default', id: 'post-button' %>
  <% end %>
  
  <% @posts.each do |post| %>
    <% post_author = logged_in? ? post.user.name : '???????' %>
    <div class="well">
      <p class="post-body"><%= post.body %></p>
      <span class="owner">
        <em><%= post.created_at.strftime('%b. %d, %Y') %></em>
        <br />
        <em>By:</em> <%= post_author %>
      </span>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<% provide(:title, "New Post") %>

<h1>New post</h1>
<div class="container-fluid col-md-6 col-md-offset-3">
  <div class="well">
    <% if @post.errors.any? %>
      <div id="error_explanation">
        <div class="alert alert-danger">
          This form contains <%= pluralize(@post.errors.count, 'error') %>.
        </div>
        <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_for @post do |f| %>
      
      <%= f.label :body, "Sneakrets:" %>
      <%= f.text_area :body, class: 'form-control' %>

      <%= f.submit "Submit post", class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<h1>About</h1>
<div class="container-fluid col-md-6 col-md-offset-3">
  <div class="well">
    <p>
      This website was built as part of the Rails course of 
      <a href="http://www.theodinproject.com/">The Odin Project</a>.  Members 
      of the website can create public posts, any only other members can learn 
      the identity of the posts' author.  It's like a secret clubhouse where 
      one can post anonymous messages to the general public.
    </p>
    <p>Use one of the following credentials to log in:</p>
    <table class="table table-striped table-bordered">
      <tr>
        <th>email</th>
        <th>password</th>
      </tr>
      <tr>
        <td>chris@example.com</td>
        <td>foobar</td>
      </tr>
      <tr>
        <td>joshua@example.com</td>
        <td>foobar</td>
      </tr>
      <tr>
        <td>melissa@example.com</td>
        <td>foobar</td>
      </tr>
      <tr>
        <td>tim@example.com</td>
        <td>foobar</td>
      </tr>
    </table>
  </div>
</div>